name: tpc_evo_slim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - jupyter=1.1.1
  - jupyterlab=4.3.5
  - numpy=2.2.5
  - scipy=1.15.2
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - ipympl=0.9.7
  - voila=0.5.8
  - pandas=2.2.3
  - tskit=0.6.0
  - slim=5.0
  - msprime=1.3.4
  - ipykernel=6.29.5
  - ffmpeg=7.1.1
